# Generated by Django 6.0 on 2025-12-22 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('link', models.URLField()),
                ('image', models.ImageField(upload_to='collections_images/')),
            ],
        ),
        migrations.AlterField(
            model_name='product',
            name='images',
            field=models.ImageField(upload_to='product_images/'),
        ),
        migrations.AddField(
            model_name='product',
            name='collections',
            field=models.ManyToManyField(related_name='products', to='shop.collection'),
        ),
    ]
